// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class MemberToday
{
    public string Guid { get; set; }

    public string MemberName { get; set; }

    public DateOnly TodayDate { get; set; }

    public string ClassName { get; set; }
}