// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Table1
{
    public string Guid { get; set; }

    public string Name { get; set; }

    public int? Age { get; set; }

    public string Ip { get; set; }
}